# Generated by Django 5.2 on 2025-05-07 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_word_root'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='instance_count',
            field=models.IntegerField(default=0),
        ),
    ]
