# Generated by Django 5.2 on 2025-05-07 21:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_userword_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userword',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='userword',
            constraint=models.UniqueConstraint(fields=('user', 'word'), name='unique_user_word'),
        ),
    ]
