# Generated by Django 5.2 on 2025-05-08 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_userword_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('words', models.ManyToManyField(to='api.word')),
            ],
        ),
        migrations.CreateModel(
            name='WordSetVideoScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.video')),
                ('word_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_scores', to='api.wordset')),
            ],
            options={
                'unique_together': {('word_set', 'video')},
            },
        ),
    ]
