# Generated by Django 5.2 on 2025-05-14 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_wordset_wordsetvideoscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='word_set',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.wordset'),
        ),
    ]
